### ISSUE TITLE
Lm393

### ISSUE THREAD

**Issue by andrisruse** [AbdouSam/arduino-sound-detector#1]
Is it a sound sensor module?

**Comment by AbdouSam** [comment]
Yes, it is a microphone coupled with an op amp and a comparator. There is a
variable resistor to set the thrshold. The output of the sensor is digital.
Zeo if the sound is blow threshold and one if the sound level is above
threshold.

andrisruse ***@***.***> schrieb am Fr., 30. Juli 2021, 21:04:
