### ISSUE TITLE
Project

### ISSUE THREAD

**Issue by andrisruse** [AbdouSam/arduino-sound-detector#3]
This project should be connect to computer or we can use adapter?

**Comment by AbdouSam** [comment]
No, it was a project for someone who wanted to detect baby cries for
parents using the LM393. The program simply detect repeating sound peak in
way that resembles a baby cry pattern. It does not connect to a PC.


andrisruse ***@***.***> schrieb am Mo., 2. Aug. 2021, 12:27:

**Comment by andrisruse** [comment]
When we use the python script? I run the python script and it said "Indexerror: index 176400 is out of bounds for axis 0 with size 176400"
How can i fix it?
