### ISSUE TITLE
Python file

### ISSUE THREAD

**Issue by andrisruse** [AbdouSam/arduino-sound-detector#5]
When I run the python code, it's worked and I got some number, just like array and a window named figure 1. What I will do with that?

**Comment by AbdouSam** [comment]
Are you searching for something in particular? It s been some time i don't really remember the details, but the python script is straight forward, as i explained in the previous questions you asked, the output of the script is the duration of peaks and repeating peaks. you can go back to previous issues you opened i have answered what i can.

The script takes the .wav sound file, filter it out using `butter worth low pass filter' and compare with a desired amplitude to decide whether it is a peak of sound or not.
you need to tweak in the values in the script to get the desired output.
